version: '3.3'
services:
  db:
    image: postgres:12.4
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    env_file:
      - ../baskhome/baskhomeBackend/.env

  backend:
#    image: georgehubdock/foodgram:latest
    build:
      context: ../baskhome/baskhomeBackend
      dockerfile: ../baskhome/baskhomeBackend/Dockerfile
    restart: always
    depends_on:
      - db
    volumes:
      - static_value:/code/static/
      - media_value:/code/media/
    env_file:
      - ../baskhome/baskhomeBackend/.env

  nginx:
    image: nginx:1.20.1
    ports:
      - "80:80"
    volumes:
      - ./nginx.conf:/etc/nginx/conf.d/default.conf
      - static_value:/static/
      - media_value:/media/

volumes:
  postgres_data:
  static_value:
  media_value: