version: '3.3'

services:
  db:
    image: postgres:12.4
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    env_file:
      - ./.env

  backend:
    image: georgehubdock/baskhome:latest
    restart: always
    depends_on:
      - db
    volumes:
      - static_value:/code/static/
      - media_value:/code/media/
    env_file:
      - ./.env

  nginx:
    image: nginx:1.20.2
    restart: unless-stopped
    volumes:
      - ./data/nginx:/etc/nginx/conf.d
      - static_value:/static/
      - media_value:/media/
      - ./data/certbot/conf:/etc/letsencrypt
      - ./data/certbot/www:/var/www/certbot
    ports:
      - "80:80"
      - "443:443"
    command: "/bin/sh -c 'while :; do sleep 6h & wait $${!}; nginx -s reload; done & nginx -g \"daemon off;\"'"
    depends_on:
      - backend

  certbot:
    image: certbot/certbot
    restart: unless-stopped
    volumes:
      - ./data/certbot/conf:/etc/letsencrypt
      - ./data/certbot/www:/var/www/certbot
    entrypoint: "/bin/sh -c 'trap exit TERM; while :; do certbot renew; sleep 12h & wait $${!}; done;'"

volumes:
  postgres_data:
  static_value:
  media_value:
