# Generated by Django 2.2.10 on 2021-12-20 19:39

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0002_auto_20211220_1904'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='price',
            name='slug',
        ),
        migrations.AddField(
            model_name='price',
            name='product',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='prices', to='shop.Product'),
            preserve_default=False,
        ),
    ]
