# Generated by Django 2.2.10 on 2021-12-20 20:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0003_auto_20211220_1939'),
    ]

    operations = [
        migrations.AddField(
            model_name='price',
            name='slug',
            field=models.SlugField(default=1, max_length=100),
            preserve_default=False,
        ),
    ]
